import { v4 as uuidv4 } from 'uuid'

export type FormProps = {
  id: string
  type?: 'email' | 'text' | 'password' | 'number'
  inputType: 'select' | 'input' | 'textarea'
  options?: { value: string; label: string; id: string }[]
  label?: string
  placeholder: string
  name: string
  lines?: number
}

export const USER_SIGNUP_FORM: FormProps[] = [
  {
    id: uuidv4(),
    type: 'text',
    inputType: 'input',
    placeholder: 'Enter your full name',
    name: 'name',
  },
  {
    id: uuidv4(),
    type: 'email',
    inputType: 'input',
    placeholder: 'Enter your email address',
    name: 'email',
  },
  {
    id: uuidv4(),
    type: 'text',
    inputType: 'input',
    placeholder: 'Enter your username',
    name: 'username',
  },
  {
    id: uuidv4(),
    type: 'password',
    inputType: 'input',
    placeholder: 'Enter your password',
    name: 'password',
  },
  {
    id: uuidv4(),
    type: 'password',
    inputType: 'input',
    placeholder: 'Please confirm your password',
    name: 'confirmPassword',
  },
]

export const USER_SIGNIN_FORM: FormProps[] = [
  {
    id: uuidv4(),
    type: 'email',
    inputType: 'input',
    placeholder: 'Enter your email address',
    name: 'email',
  },
  {
    id: uuidv4(),
    type: 'password',
    inputType: 'input',
    placeholder: 'Enter your password',
    name: 'password',
  },
]

export const CREATE_LISTING_FORM: FormProps[] = [
  {
    id: uuidv4(),
    type: 'text',
    inputType: 'input',
    placeholder: 'Whats your dorm called?',
    name: 'name',
    label: 'Dorm Name',
  },
  {
    id: uuidv4(),
    inputType: 'textarea',
    placeholder: 'Give a description that stands out',
    name: 'description',
    label: 'Dorm Description',
    lines: 20,
  },
]

export const CREATE_DORM_ROOM_PAYMENT_PLAN: FormProps[] = [
  {
    id: uuidv4(),
    type: 'text',
    inputType: 'select',
    placeholder: 'Select a room type',
    name: 'room',
    label: 'Dorm Room',
    options: [
      {
        id: uuidv4(),
        value: '1+1',
        label: '1+1',
      },
      {
        id: uuidv4(),
        value: '2+1',
        label: '2+1',
      },
      {
        id: uuidv4(),
        value: '3+1',
        label: '3+1',
      },
      {
        id: uuidv4(),
        value: 'double + kitehen',
        label: 'Double + Kitchen',
      },
      {
        id: uuidv4(),
        value: 'Single + kitehen',
        label: 'Single + Kitchen',
      },
    ],
  },
  {
    id: uuidv4(),
    type: 'text',
    inputType: 'input',
    placeholder: 'Add a price for your room',
    name: 'price',
    label: 'Room Price',
  },
]

export const UPDATE_USER_INFO: FormProps[] = [
  {
    id: uuidv4(),
    type: 'text',
    inputType: 'input',
    placeholder: 'Enter your fullname...',
    name: 'fullname',
    label: 'Full Name',
  },
  {
    id: uuidv4(),
    type: 'text',
    inputType: 'input',
    placeholder: 'Enter your username...',
    name: 'username',
    label: 'User Name',
  },
  {
    id: uuidv4(),
    type: 'text',
    inputType: 'input',
    placeholder: 'Enter your address...',
    name: 'address',
    label: 'User Address',
  },
  {
    id: uuidv4(),
    type: 'text',
    inputType: 'input',
    placeholder: 'Enter your Phone no...',
    name: 'phone',
    label: 'User Phone',
  },
  {
    id: uuidv4(),
    inputType: 'select',
    placeholder: 'Select a country',
    name: 'country',
    label: 'User Country',
    options: [
      { id: uuidv4(), value: 'afghan', label: 'Afghanistan' },
      { id: uuidv4(), value: 'albanian', label: 'Albania' },
      { id: uuidv4(), value: 'algerian', label: 'Algeria' },
      { id: uuidv4(), value: 'american', label: 'United States' },
      { id: uuidv4(), value: 'andorran', label: 'Andorra' },
      { id: uuidv4(), value: 'angolan', label: 'Angola' },
      {
        id: uuidv4(),
        value: 'antiguans and barbudans',
        label: 'Antigua and Barbuda',
      },
      { id: uuidv4(), value: 'argentinean', label: 'Argentina' },
      { id: uuidv4(), value: 'armenian', label: 'Armenia' },
      { id: uuidv4(), value: 'australian', label: 'Australia' },
      { id: uuidv4(), value: 'austrian', label: 'Austria' },
      { id: uuidv4(), value: 'azerbaijani', label: 'Azerbaijan' },
      { id: uuidv4(), value: 'bahamian', label: 'Bahamas' },
      { id: uuidv4(), value: 'bahraini', label: 'Bahrain' },
      { id: uuidv4(), value: 'bangladeshi', label: 'Bangladesh' },
      { id: uuidv4(), value: 'barbadian', label: 'Barbados' },
      { id: uuidv4(), value: 'belarusian', label: 'Belarus' },
      { id: uuidv4(), value: 'belgian', label: 'Belgium' },
      { id: uuidv4(), value: 'belizean', label: 'Belize' },
      { id: uuidv4(), value: 'beninese', label: 'Benin' },
      { id: uuidv4(), value: 'bhutanese', label: 'Bhutan' },
      { id: uuidv4(), value: 'bolivian', label: 'Bolivia' },
      {
        id: uuidv4(),
        value: 'bosnian or herzegovinian',
        label: 'Bosnia and Herzegovina',
      },
      { id: uuidv4(), value: 'botswana', label: 'Botswana' },
      { id: uuidv4(), value: 'brazilian', label: 'Brazil' },
      { id: uuidv4(), value: 'british', label: 'United Kingdom' },
      { id: uuidv4(), value: 'bruneian', label: 'Brunei' },
      { id: uuidv4(), value: 'bulgarian', label: 'Bulgaria' },
      { id: uuidv4(), value: 'burkinabe', label: 'Burkina Faso' },
      { id: uuidv4(), value: 'burundian', label: 'Burundi' },
      { id: uuidv4(), value: 'cambodian', label: 'Cambodia' },
      { id: uuidv4(), value: 'cameroonian', label: 'Cameroon' },
      { id: uuidv4(), value: 'canadian', label: 'Canada' },
      { id: uuidv4(), value: 'cape verdean', label: 'Cape Verde' },
      {
        id: uuidv4(),
        value: 'central african',
        label: 'Central African Republic',
      },
      { id: uuidv4(), value: 'chadian', label: 'Chad' },
      { id: uuidv4(), value: 'chilean', label: 'Chile' },
      { id: uuidv4(), value: 'chinese', label: 'China' },
      { id: uuidv4(), value: 'colombian', label: 'Colombia' },
      { id: uuidv4(), value: 'comoran', label: 'Comoros' },
      {
        id: uuidv4(),
        value: 'congolese',
        label: 'Democratic Republic of the Congo',
      },
      { id: uuidv4(), value: 'costa rican', label: 'Costa Rica' },
      { id: uuidv4(), value: 'croatian', label: 'Croatia' },
      { id: uuidv4(), value: 'cuban', label: 'Cuba' },
      { id: uuidv4(), value: 'cypriot', label: 'Cyprus' },
      { id: uuidv4(), value: 'czech', label: 'Czech Republic' },
      { id: uuidv4(), value: 'danish', label: 'Denmark' },
      { id: uuidv4(), value: 'djibouti', label: 'Djibouti' },
      { id: uuidv4(), value: 'dominican', label: 'Dominica' },
      { id: uuidv4(), value: 'dutch', label: 'Netherlands' },
      { id: uuidv4(), value: 'east timorese', label: 'Timor-Leste' },
      { id: uuidv4(), value: 'ecuadorian', label: 'Ecuador' },
      { id: uuidv4(), value: 'egyptian', label: 'Egypt' },
      { id: uuidv4(), value: 'emirati', label: 'United Arab Emirates' },
      { id: uuidv4(), value: 'equatorial guinean', label: 'Equatorial Guinea' },
      { id: uuidv4(), value: 'eritrean', label: 'Eritrea' },
      { id: uuidv4(), value: 'estonian', label: 'Estonia' },
      { id: uuidv4(), value: 'ethiopian', label: 'Ethiopia' },
      { id: uuidv4(), value: 'fijian', label: 'Fiji' },
      { id: uuidv4(), value: 'filipino', label: 'Philippines' },
      { id: uuidv4(), value: 'finnish', label: 'Finland' },
      { id: uuidv4(), value: 'french', label: 'France' },
      { id: uuidv4(), value: 'gabonese', label: 'Gabon' },
      { id: uuidv4(), value: 'gambian', label: 'Gambia' },
      { id: uuidv4(), value: 'georgian', label: 'Georgia' },
      { id: uuidv4(), value: 'german', label: 'Germany' },
      { id: uuidv4(), value: 'ghanaian', label: 'Ghana' },
      { id: uuidv4(), value: 'greek', label: 'Greece' },
      { id: uuidv4(), value: 'grenadian', label: 'Grenada' },
      { id: uuidv4(), value: 'guatemalan', label: 'Guatemala' },
      { id: uuidv4(), value: 'guinea-bissauan', label: 'Guinea-Bissau' },
      { id: uuidv4(), value: 'guinean', label: 'Guinea' },
      { id: uuidv4(), value: 'guyanese', label: 'Guyana' },
      { id: uuidv4(), value: 'haitian', label: 'Haiti' },
      { id: uuidv4(), value: 'herzegovinian', label: 'Bosnia and Herzegovina' },
      { id: uuidv4(), value: 'honduran', label: 'Honduras' },
      { id: uuidv4(), value: 'hungarian', label: 'Hungary' },
      { id: uuidv4(), value: 'icelander', label: 'Iceland' },
      { id: uuidv4(), value: 'indian', label: 'India' },
      { id: uuidv4(), value: 'indonesian', label: 'Indonesia' },
      { id: uuidv4(), value: 'iranian', label: 'Iran' },
      { id: uuidv4(), value: 'iraqi', label: 'Iraq' },
      { id: uuidv4(), value: 'irish', label: 'Ireland' },
      { id: uuidv4(), value: 'israeli', label: 'Israel' },
      { id: uuidv4(), value: 'italian', label: 'Italy' },
      { id: uuidv4(), value: 'ivorian', label: 'Ivory Coast' },
      { id: uuidv4(), value: 'jamaican', label: 'Jamaica' },
      { id: uuidv4(), value: 'japanese', label: 'Japan' },
      { id: uuidv4(), value: 'jordanian', label: 'Jordan' },
      { id: uuidv4(), value: 'kazakhstani', label: 'Kazakhstan' },
      { id: uuidv4(), value: 'kenyan', label: 'Kenya' },
      { id: uuidv4(), value: 'kiribati', label: 'Kiribati' },
      { id: uuidv4(), value: 'kuwaiti', label: 'Kuwait' },
      { id: uuidv4(), value: 'kyrgyz', label: 'Kyrgyzstan' },
      { id: uuidv4(), value: 'laotian', label: 'Laos' },
      { id: uuidv4(), value: 'latvian', label: 'Latvia' },
      { id: uuidv4(), value: 'lebanese', label: 'Lebanon' },
      { id: uuidv4(), value: 'mosotho', label: 'Lesotho' },
      { id: uuidv4(), value: 'liberian', label: 'Liberia' },
      { id: uuidv4(), value: 'libyan', label: 'Libya' },
      { id: uuidv4(), value: 'liechtensteiner', label: 'Liechtenstein' },
      { id: uuidv4(), value: 'lithuanian', label: 'Lithuania' },
      { id: uuidv4(), value: 'luxembourger', label: 'Luxembourg' },
      { id: uuidv4(), value: 'macedonian', label: 'North Macedonia' },
      { id: uuidv4(), value: 'malagasy', label: 'Madagascar' },
      { id: uuidv4(), value: 'malawian', label: 'Malawi' },
      { id: uuidv4(), value: 'malaysian', label: 'Malaysia' },
      { id: uuidv4(), value: 'maldivian', label: 'Maldives' },
      { id: uuidv4(), value: 'malian', label: 'Mali' },
      { id: uuidv4(), value: 'maltese', label: 'Malta' },
      { id: uuidv4(), value: 'marshallese', label: 'Marshall Islands' },
      { id: uuidv4(), value: 'mauritanian', label: 'Mauritania' },
      { id: uuidv4(), value: 'mauritian', label: 'Mauritius' },
      { id: uuidv4(), value: 'mexican', label: 'Mexico' },
      { id: uuidv4(), value: 'micronesian', label: 'Micronesia' },
      { id: uuidv4(), value: 'moldovan', label: 'Moldova' },
      { id: uuidv4(), value: 'monacan', label: 'Monaco' },
      { id: uuidv4(), value: 'mongolian', label: 'Mongolia' },
      { id: uuidv4(), value: 'montenegrin', label: 'Montenegro' },
      { id: uuidv4(), value: 'moroccan', label: 'Morocco' },
      { id: uuidv4(), value: 'mozambican', label: 'Mozambique' },
      { id: uuidv4(), value: 'namibian', label: 'Namibia' },
      { id: uuidv4(), value: 'nauruan', label: 'Nauru' },
      { id: uuidv4(), value: 'nepalese', label: 'Nepal' },
      { id: uuidv4(), value: 'new zealander', label: 'New Zealand' },
      { id: uuidv4(), value: 'ni-vanuatu', label: 'Vanuatu' },
      { id: uuidv4(), value: 'nicaraguan', label: 'Nicaragua' },
      { id: uuidv4(), value: 'nigerien', label: 'Niger' },
      { id: uuidv4(), value: 'nigerian', label: 'Nigeria' },
      { id: uuidv4(), value: 'north korean', label: 'North Korea' },
      { id: uuidv4(), value: 'northern irish', label: 'Northern Ireland' },
      { id: uuidv4(), value: 'norwegian', label: 'Norway' },
      { id: uuidv4(), value: 'omani', label: 'Oman' },
    ],
  },
]

export const STUDENT_INFO_FORM: FormProps[] = [
  {
    id: uuidv4(),
    type: 'text',
    inputType: 'input',
    placeholder: 'Enter your student Id...',
    name: 'studentId',
    label: 'Student ID',
  },
  {
    id: uuidv4(),
    type: 'text',
    inputType: 'select',
    placeholder: 'Select a department',
    name: 'department',
    label: 'Student Department',
    options: [
      { id: uuidv4(), value: 'Mechanical Engineering', label: 'MECH' },
      { id: uuidv4(), value: 'Computer Science', label: 'CS' },
      { id: uuidv4(), value: 'Electrical Engineering', label: 'EE' },
      { id: uuidv4(), value: 'Civil Engineering', label: 'CE' },
      { id: uuidv4(), value: 'Chemical Engineering', label: 'CHE' },
      { id: uuidv4(), value: 'Biomedical Engineering', label: 'BME' },
      { id: uuidv4(), value: 'Aerospace Engineering', label: 'AE' },
      { id: uuidv4(), value: 'Environmental Engineering', label: 'ENV' },
      { id: uuidv4(), value: 'Materials Science', label: 'MSE' },
      { id: uuidv4(), value: 'Industrial Engineering', label: 'IE' },
      { id: uuidv4(), value: 'Chemistry', label: 'CHEM' },
      { id: uuidv4(), value: 'Physics', label: 'PHYS' },
      { id: uuidv4(), value: 'Biology', label: 'BIO' },
      { id: uuidv4(), value: 'Mathematics', label: 'MATH' },
      { id: uuidv4(), value: 'Psychology', label: 'PSYCH' },
      { id: uuidv4(), value: 'Art History', label: 'AH' },
      { id: uuidv4(), value: 'English Literature', label: 'ENGL' },
      { id: uuidv4(), value: 'History', label: 'HIST' },
      { id: uuidv4(), value: 'Philosophy', label: 'PHIL' },
      { id: uuidv4(), value: 'Political Science', label: 'POLI SCI' },
      { id: uuidv4(), value: 'Economics', label: 'ECON' },
      { id: uuidv4(), value: 'Sociology', label: 'SOC' },
      { id: uuidv4(), value: 'Anthropology', label: 'ANTHRO' },
      { id: uuidv4(), value: 'Linguistics', label: 'LING' },
      { id: uuidv4(), value: 'Geography', label: 'GEOG' },
      { id: uuidv4(), value: 'Music', label: 'MUS' },
      { id: uuidv4(), value: 'Theater', label: 'THEATR' },
      { id: uuidv4(), value: 'Dance', label: 'DANCE' },
      { id: uuidv4(), value: 'Visual Arts', label: 'VIS ARTS' },
      { id: uuidv4(), value: 'Finance', label: 'FIN' },
      { id: uuidv4(), value: 'Marketing', label: 'MKTG' },
      { id: uuidv4(), value: 'Management', label: 'MGMT' },
      { id: uuidv4(), value: 'Human Resources', label: 'HR' },
      { id: uuidv4(), value: 'Operations Management', label: 'OPSMGT' },
      { id: uuidv4(), value: 'Entrepreneurship', label: 'ENTR' },
      { id: uuidv4(), value: 'International Business', label: 'INTL BUS' },
      { id: uuidv4(), value: 'Supply Chain Management', label: 'SCM' },
      { id: uuidv4(), value: 'Statistics', label: 'STAT' },
      { id: uuidv4(), value: 'Public Health', label: 'PUB HLTH' },
      { id: uuidv4(), value: 'Nursing', label: 'NURS' },
      { id: uuidv4(), value: 'Medicine', label: 'MED' },
      { id: uuidv4(), value: 'Dentistry', label: 'DENT' },
      { id: uuidv4(), value: 'Pharmacy', label: 'PHARM' },
      { id: uuidv4(), value: 'Law', label: 'LAW' },
    ],
  },
]
